plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.kjngstar.tavernchatreader'
    compileSdk 35

    defaultConfig {
        applicationId 'io.github.kjngstar.tavernchatreader'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.0.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
